import "./globals.css";
import Header from "./_components/Header";
import QueryProvider from "./_components/QueryProvider";
import { ThemeProvider } from "next-themes"
import DarkAndLight from "./_components/ToggleButton";
import { Lora } from 'next/font/google'



const lora = Lora({
  weight: ['400','500'],
  subsets: ['latin'],
  variable: '--font-poppins',
  display: 'swap',
})
 


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${lora.className} antialiased relative bg-slate-100 dark:bg-black`}
      >
       <ThemeProvider attribute="class">
          <Header/>
          <DarkAndLight/>
        <main>
<QueryProvider>

        {children}
</QueryProvider>
        </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
